apiVersion: v1
kind: Template
labels:
  template: janusgraph-builder
metadata:
  annotations:
    description: janusgraph container
    iconClass: janusgraph
    tags: janusgraph,ai-stack-builder
  name: janusgraph-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: janusgraph
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: janusgraph
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: janusgraph:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: janusgraph
          - name: BUILD_LOGLEVEL
            value: "2"
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/goern/janusgraph-openshift.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: images/janusgraph
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master